pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Common

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    echo "registry=https://pkgs.dev.azure.com/desarrollooticoptimus/optimus/_packaging/FrontComponent/npm/registry/" > .npmrc
    echo "//pkgs.dev.azure.com/desarrollooticoptimus/optimus/_packaging/FrontComponent/npm/registry/:username=desarrollooticoptimus" >> .npmrc
    echo "//pkgs.dev.azure.com/desarrollooticoptimus/optimus/_packaging/FrontComponent/npm/registry/:_password=$(registry_npm)" >> .npmrc
    echo "//pkgs.dev.azure.com/desarrollooticoptimus/optimus/_packaging/FrontComponent/npm/registry/:email=$(registry_email_npm)" >> .npmrc
    echo "//pkgs.dev.azure.com/desarrollooticoptimus/optimus/_packaging/FrontComponent/npm/:username=desarrollooticoptimus" >> .npmrc
    echo "//pkgs.dev.azure.com/desarrollooticoptimus/optimus/_packaging/FrontComponent/npm/:_password=$(registry_npm)" >> .npmrc
    echo "//pkgs.dev.azure.com/desarrollooticoptimus/optimus/_packaging/FrontComponent/npm/:email=$(registry_email_npm)" >> .npmrc
    echo "always-auth=true" >> .npmrc
  displayName: 'Set up .npmrc'

- script: npm install --legacy-peer-deps
  displayName: 'Install dependencies'

- script: npm publish --scope=@tuscope
  displayName: 'Publish to Azure Artifacts'